"""
Script documentation
- Tool parameters are accessed using arcpy.GetParameter() or
                                     arcpy.GetParameterAsText()
- Update derived parameter values using arcpy.SetParameter() or
                                        arcpy.SetParameterAsText()
"""
import os
from zipfile import ZipFile
import traceback
import inspect

import arcpy


def script_tool(project_folder="", source_zip_file=""):
    """Script code goes below"""
    try:

        # aprx = arcpy.mp.ArcGISProject("CURRENT")
        # aprx.save()
        # home_folder = aprx.homeFolder

        arcpy.AddMessage(project_folder)
        out_data_path = rf"{project_folder}\Dataset_Shapefiles"
        arcpy.AddMessage(out_data_path)

        # Change Directory
        os.chdir(out_data_path)

        arcpy.AddMessage(f"Un-Zipping files from {os.path.basename(source_zip_file)}")
        with ZipFile(source_zip_file, mode="r") as archive:
            for file in archive.namelist():
                archive.extract(file, ".")
                del file
        del archive

        arcpy.AddMessage(
            f"Done Un-Zipping files from {os.path.basename(source_zip_file)}"
        )
        del project_folder, source_zip_file

    except arcpy.ExecuteWarning:
        arcpy.AddWarning(
            f"ArcPy Execute Warning in '{inspect.stack()[0][3]}':\n{arcpy.GetMessages(1)}"
        )
    except arcpy.ExecuteError:
        arcpy.AddError(
            f"ArcPy Execute Error in '{inspect.stack()[0][3]}':\n{arcpy.GetMessages(2)}"
        )
        arcpy.AddError("Traceback:\n")
        traceback.print_exc()
    except SystemExit:
        # This is not an error, so we allow the script to exit.
        pass
    except Exception as e:
        arcpy.AddError(
            f"An unexpected error occurred in '{inspect.stack()[0][3]}': {e}"
        )
        arcpy.AddError("Traceback:")
        traceback.print_exc()
    else:
        arcpy.AddMessage("\nScript finished successfully.\n")
    finally:
        arcpy.AddMessage(f"\n{'--End' * 10}--")

if __name__ == "__main__":
    try:

        project_folder = arcpy.GetParameterAsText(0)
        if not project_folder:
            # project_name = "February-1-2026"
            # project_name = "August-1-2025"
            project_name = "June-1-2026"
            project_folder = os.path.join(os.path.expanduser('~'), f"Documents\\ArcGIS\\Projects\\DisMAP\\ArcGIS-Analysis-Python\\{project_name}")
        else:
            pass

        source_zip_file = arcpy.GetParameterAsText(1)
        if not source_zip_file:
            source_zip_file = os.path.join(os.path.expanduser('~'), "Documents\\ArcGIS\\Projects\\DisMAP\\ArcGIS-Analysis-Python\\Initial-Data\\Dataset-Shapefiles-20260601.zip")
        else:
            pass

        # print(project_folder)
        # print(source_zip_file)

        script_tool(project_folder, source_zip_file)

        arcpy.SetParameterAsText(1, "Result")

        del project_folder, source_zip_file

    except SystemExit:
        # This is not an error, so we allow the script to exit.
        pass
    except arcpy.ExecuteError:
        arcpy.AddError(arcpy.GetMessages(2))
        traceback.print_exc()
    except Exception:
        traceback.print_exc()


# This is an autogenerated comment.
