#!/usr/bin/env python3
# For relative imports to work in Python 3.11
import importlib
user_credentials = importlib.import_module("DisMap-ArcGIS-Analysis-Python.user_credentials")

# This is an autogenerated comment.
